[package]
name = "pow"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dev-dependencies.criterion]
version = "0.3"
features = ["html_reports"]

[[bench]]
name = "bench"
harness = false
